### ISSUE TITLE
Unable to shorten link to `tel://`

### ISSUE THREAD

**Issue by kaovilai** [jstayton/suri#21]
Example
```json
    "police": "tel://911"
```

```

`TemplateDataParseError` was thrown
--
15:10:53.017 | > Unexpected string in JSON at position 141
15:10:53.017 |  
15:10:53.017 | `SyntaxError` was thrown:
15:10:53.017 | SyntaxError: Unexpected string in JSON at position 141
15:10:53.017 | at parse (<anonymous>)
15:10:53.018 | at TemplateData._parseDataFile (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:351:16)
15:10:53.018 | at async TemplateData.getAllGlobalData (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
15:10:53.018 | at async TemplateData.getData (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)


```

Suri 0.4.0

**Comment by jstayton** [comment]
Hey @kaovilai,

Hmmm, I'm not having any trouble with that on my end. Is that example in a proper JSON object?

```json
{
  "police": "tel://911"
}
```

**Comment by kaovilai** [comment]
Found a typo. Works now. Closing. Thanks!
